showroom = set()
showroom.add("Silverado")
showroom.add("Corvette")
showroom.add("Mustang")
showroom.add("Star Destroyer")
print(len(showroom))
showroom.add("Star Destroyer")
print(showroom)
showroom.update({"Ram", "Equinox"})
print(showroom)
showroom.discard("Mustang")

junkyard = {"Silverado", "Civic", "Impala", "X-Wing"}
print(junkyard.intersection(showroom))
showroom = showroom.union(junkyard)
print(showroom)
junkyard.discard("Civic")
junkyard.discard("Impala")
junkyard.discard("X-Wing")
print(junkyard)
