showroom = set()
showroom.add("Silverado")
showroom.add("Corvette")
showroom.add("Mustang")
showroom.add("Star Destroyer")
print(len(showroom))
showroom.add("Star Destroyer")
print(showroom)
showroom.update({"Ram", "Equinox"})
print(showroom)
showroom.discard("Mustang")